# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
image:
  file: .gitpod.Dockerfile



tasks:
  - name: Script Task
    init: echo 'init script'
      # echo 'Initializing...'
      # sudo apt-get update && sudo apt-get install -y xvfb
      #export DISPLAY=:99
      #./path/to/your/build_or_setup_script.sh

      # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds

    # command: echo 'start script'
    #   echo "Running..."
    #   sudo Xvfb :99 -screen 0 1024x768x16 &
    #   export DISPLAY=:99
    #   ps aux | grep Xvfb
    #   chmod +x ./cds1.sh
    #   sudo ./cds1.sh
    #   #./path/to/your/linux_video_demo

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
# ports:
  # .gitpod.yml

ports:
  - port: 5553
    onOpen: ignore  # Keeps port open in background without prompt
  - port: 5554
    onOpen: ignore
  - port: 5555
    onOpen: ignore

#   - name: Frontend
#     description: Port 3000 for the frontend
#     port: 3000
#     onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart